### ISSUE TITLE
Аватар спикера в формате .PNG не поддерживается

### ISSUE THREAD

**Issue by ilabutin** [DotNetRu/Server#102]
Попробовал заимпортить текущий Аудит в локальную базу. Сломался на спикере Alexey-Matveev. Причина: у него аватарка лежит как `Avatar.png`, а код поиска аватара в Server такой:

```
var avatar = content.First(x => x.Name == "avatar.jpg");
var avatarSmall = content.FirstOrDefault(x => x.Name == "avatar.small.jpg");
```

**Comment by kulakovt** [comment]
@ilabutin , это бага в Аудите. [Исправил](https://github.com/DotNetRu/Audit/pull/124).

**Comment by kulakovt** [comment]
Аватар спикера это фотография. Для хранения фотографий PNG подходит плохо. Поэтому все фотографии должны храниться в JPEG. С логотипами партнёров ситуация противоположная - там все логотипы обязаны быть в PNG.

**Comment by ilabutin** [comment]
Раз исправлено, то закрываем.
