### ISSUE TITLE
Экспорт данных из сервера через API

### ISSUE THREAD

**Issue by ilabutin** [DotNetRu/Server#103]
Существующий DotNetRuServer.Exporter умеет брать данные напрямую из БД. Поскольку сейчас в проекте используется InMemory БД, то такой вариант не работает в production.

Необходимо модифицировать Exporter чтобы он умел работать через API (либо существующее, либо новое/дополнительное).

**Comment by kulakovt** [comment]
Мне кажется, что оба importer и exporter должны работать через API. Мало ли какой storage мы захотим использовать внутри. Функциональность от этого не должна разваливаться.

**Comment by ilabutin** [comment]
Для импорта API есть. Я проверю что оно работает и потом надо будет переделать importer. Про это отдельно напишу issue. Просто без экспорта вообще пользоваться невозможно.

**Comment by egorikas** [comment]
@ilabutin а просто из любопытства
в каком виде переделать импорте?

**Comment by ilabutin** [comment]
Для этого я создал #105. Хочется в импортер передавать github token и пусть он просто дёрнет API. Ничего сложного но тогда будет пара тулов - для импорта и экспорта. Понятно что для импорта было бы достаточно curl или что-то подобное использовать, но поскольку с экспортером так просто не получится (всё равно нужна логика для раскладывания по файловой системе), то хочется иметь пару тулов.

А может вообще объединить их в один и деплоить как dotnet global tool? 

@egorikas

**Comment by ilabutin** [comment]
По результатам разговора с @egorikas и @AnatolyKulakov решили что новое API будет возвращать  готовый .ZIP архив куда будет всё уже сложено. Дальше этот .ZIP уже вручную сравниваем с github и коммитим.

**Comment by kulakovt** [comment]
@ilabutin Неплохо было бы ещё сделать, чтобы на клиенте мне этот zip не пришлось бы руками раскладывать по нужным директориям.

Хочется запустить
`Export --localPath "C:\Audit" ...`
И получить локальную копию Аудита полностью такую какова сейчас модель на сервере. И не знать не про какие zip файлы.

**Comment by ilabutin** [comment]
Да, согласен, забыл упомянуть. API возвращает zip, а DotNetRuServer.Exporter раскладывает всё по папкам
