### ISSUE TITLE
Ошибка импорта данных на сервер через API

### ISSUE THREAD

**Issue by ilabutin** [DotNetRu/Server#104]
Если вызвать существующий POST /api/import и указать github token, то возвращается error 500 с таким текстом:
InvalidOperationException: Unable to resolve service for type &#x27;DotNetRuServer.Application.Importer&#x27; while attempting to activate &#x27;DotNetRuServer.Controllers.ImportController&#x27;

**Comment by egorikas** [comment]
@ilabutin https://github.com/DotNetRu/Server/pull/106/files я там немножко накосячил, сейчас все работает

**Comment by ilabutin** [comment]
Исправлено (см. PR #106 )
