### ISSUE TITLE
Добавить возможность вызова API импорта через Importer

### ISSUE THREAD

**Issue by ilabutin** [DotNetRu/Server#105]
В настоящее время DotNetRuServer.Importer умеет импортировать данные только напрямую в БД.
Нужно добавить возможность указать github token и потом вызывать POST /api/import для импорта непосредственно из Аудита.

**Comment by egorikas** [comment]
Я немного не понимаю сути задачи, можно разъяснить?

**Comment by ilabutin** [comment]
Я хочу иметь возможность из командной строки своей ОС запустить импорт текущего состояния в DotNetRu Server.
В идеале нужно кнопку в UI, но этого ждать долго. Поэтому для начала просто хочется запускать
```
DotNetRuServer.Importer --githubtoken XXXXXXX --serverURL https://www....
```
и после этого будет из гитхаба импортится данные в сервер (посредством вызова POST /api/import)
