### ISSUE TITLE
Больше GitHub'а

### ISSUE THREAD

**Issue by rafaelldi** [DotNetRu/Server#116]
Вчера [стали доступны](https://github.blog/2019-11-13-universe-day-one/) GitHub Actions (для CI/CD) и GitHub Packages (для хранения, например, докер образов). Что думаете о том, что бы перенести всё в гитхаб, вроде бы удобнее, когда всё в одном месте?

**Comment by kulakovt** [comment]
@rafaelldi CI/CD можно попробовать.
Docker образ должен храниться там, откуда его способна забрать Azure автоматически и развернуть у себя. Пока это только DockerHub.

А какое «удобство» имеется ввиду?

**Comment by rafaelldi** [comment]
Не нужно переключаться между сервисами, всё в одном месте. Например, что-то не собралось, можно в этом же репозитории посмотреть, что случилось. Понятно, что это спорно, и для каждого удобно разное.

**Comment by egorikas** [comment]
Я настраивал Github actions на текущем рабочем проекте. Штука рабочая, но очень ограниченная местами. Для наших целей подойдет. Без проблем можно собирать Docker и пушить. Секреты хранятся через github creadentials с этим тоже проблем не возникает

**Comment by rafaelldi** [comment]
Для ажуры, кстати, есть [такой репозиторий](https://github.com/Azure/actions) с actions.

**Comment by egorikas** [comment]
я тут набросал https://github.com/DotNetRu/Server/pull/120

**Comment by kulakovt** [comment]
В новой версии #125 сделаем свой CI
