### ISSUE TITLE
Начальная настройка проекта

### ISSUE THREAD

**Issue by ilabutin** [DotNetRu/Server#127]
Для удобной работы необходимо произвести начальную настройку проекта:

- [ ] пустое blazor приложение (.NET 5)
- [ ] автоматический билд
- [ ] тестовый проект и установленный тестовый фреймворк в нём
- [ ] автоматический запуск тестов на CI
- [ ] настроенный логер
- [ ] настроенная система конфигураций (Configuration)
- [ ] настроенные контейнер зависимостей (DI)
- [ ] максимальный уровень warnings
- [ ] treat warnings as error
- [ ] nullable reference types
- [ ] editor config

**Comment by zetroot** [comment]
Как то будем собирать test coverage? Не то что бы я от всей души верил в то, что это панацея, но как ачивка ничего;-)

**Comment by zetroot** [comment]
Для тестирования blazor components надо завести ещё тестовый проект на [bunit](https://bunit.dev/docs/getting-started/) 
@ilabutin, чего ещё нам не хватает для старта?

**Comment by ilabutin** [comment]
Да вроде всё есть. Кажется что можно закрывать таску. Согласен?

**Comment by zetroot** [comment]
Я хочу прикрутить тестирование blazor pages, ну и накинуть туда пару тестов для иллюстрации, а то это получится очень большой пласт не тестированного кода. Можно вынести это в новый issue, а эту действительно закрыть

**Comment by zetroot** [comment]
Добавил отдельный issue #143 для задачи тестирования страниц.

**Comment by ilabutin** [comment]
ок, закрываю
