### ISSUE TITLE
GitHub: авторизация

### ISSUE THREAD

**Issue by ilabutin** [DotNetRu/Server#128]
Нужно научиться авторизовываться в Гитхабе.
Первый шаг - personal access token
В идеале - OAuth.

**Comment by zetroot** [comment]
Описание OAuth flow есть [здесь](https://octokitnet.readthedocs.io/en/latest/oauth-flow/)
Меня смущает требование сохранения в секрете `client secret`. Как мы сможем этого добиться, если приложение выполняется целиком на стороне клиента?

**Comment by ilabutin** [comment]
А вот похоже что гитхаб такого не умеет.. [Вот тут](https://stackoverflow.com/questions/55358004/github-octokit-rest-js-oauth-for-single-page-applications) автор Octokit (JS части) пишет что для OAuth нужен бэкенд. Либо самим запрашивать логин/пароль, но это как-то несекьюрно.

**Comment by ilabutin** [comment]
В большинстве мест [предлагают использовать простой бэкенд](https://www.kmaschta.me/blog/2017/03/04/github-oauth-authentication-without-server/) чисто для получения токена. В принципе, Azure Functions или AWS Lambda умеют какое-то количество бесплатного CPU в месяц, так что можно рассмотреть в будущем.
Но пока обойдемся спрашивать PAT.

**Comment by zetroot** [comment]
Ок, запаркуем OAuth покамест.

**Comment by ilabutin** [comment]
Для первого прототипа сойдёт то что есть. Улучшения в отдельный issue.
