### ISSUE TITLE
Core: бизнес модели домена

### ISSUE THREAD

**Issue by ilabutin** [DotNetRu/Server#130]
Для работы с митапами нужна модель предметной области, независимая от модели хранения.

**Comment by zetroot** [comment]
Мне тут не хватает знаний предметной области. 
Я так понимаю, что [модель в Auditor](https://github.com/DotNetRu/Auditor/tree/master/src/Data/Model) вполне полна. 
Попробую оттолкнуться от этого.

**Comment by kulakovt** [comment]
Да, возьми её. Просто удали лишние интерфейсы и методы. Тебе нужны только чистые классы и поля. А дальше уже накручивайте своими хотелками.

**Comment by zetroot** [comment]
Может попробуем `record`?

**Comment by ilabutin** [comment]
Считаем что модель есть. Дополнения будут отдельными issue если потребуется
