### ISSUE TITLE
Настроить сборку Docker контейнера

### ISSUE THREAD

**Issue by kulakovt** [DotNetRu/Server#14]
Работа приложения не должна зависеть от конкретного хостинга и окружения.

Поэтому необходимо создать и поддерживать образ Docker контейнера. В контейнер должны входить все проекты, необходимые для полноценной работы сервиса ([Server](https://github.com/DotNetRu/Server) и [WebUI](https://github.com/DotNetRu/WebUI)).

Для уменьшения издержек на хостинг, следует предпочесть Linux решение.

**Comment by kulakovt** [comment]
[axle-h/Retro.Net](https://github.com/axle-h/Retro.Net/blob/master/Dockerfile) - хороший пример подходящего по требованиям контейнера

**Comment by kulakovt** [comment]
@d2funlife , какой статус задачи? Dockerfile у нас есть, hub есть. Я так понимаю, ещё нет загрузки образа после билда в hub? Что-то ещё?

**Comment by kulakovt** [comment]
Сделал Ажурный хостинг на базе официального контейнера:
https://dotnetru.azurewebsites.net/
Пока не знаю будет ли он подхватывать новую версию контейнера.

**Comment by d2funlife** [comment]
@AnatolyKulakov вернул [PR ](https://github.com/DotNetRu/Server/pull/39), который по ошибке отменил.
Что осталось не законченным:
- публикация Github Releases 
- тригер на запуск скрипта обновления приложения. Из коробки решения для docker + Azure нет, остальные варианты тригеров более похожи на костыль, а не решение.

В связи с появлением [Azure Pipelines](https://azure.microsoft.com/ru-ru/services/devops/pipelines/) предлагаю использовать его. Плюс есть интеграция в их же хостинг.

**Comment by d2funlife** [comment]
[Azure Pipelines](https://azure.microsoft.com/ru-ru/services/devops/pipelines/) для open source проектов бесплатно

**Comment by kulakovt** [comment]
Я когда настраивал Azure хостинг, там были намёки на автоматическое обновление из Docker Hub. Надо просто проверить.

@d2funlife , ты для этого хотел Pipelines или для обновления какого-то другого приложения?

**Comment by d2funlife** [comment]
да, именно связать этап обновления на хостинге и готовый образ docker

**Comment by kulakovt** [comment]
Тогда скорее всего это должно работать и сейчас. Давай просто проверим (опубликуем новый docker образ) и после этого будет думать. Судя по описанию Pipelines призваны конкурировать с AppVeyor.

**Comment by d2funlife** [comment]
@AnatolyKulakov нужно дернуть сборку, в develop ветке CI [отработал ](https://ci.appveyor.com/project/AnatolyKulakov/server/builds/19414119) на обе платформы, master сейчас, судя по истории, собрал только под windows. Если все правильно сделали, должны будут обновиться [docker ](https://hub.docker.com/r/dotnetru/server/tags/) и host

**Comment by kulakovt** [comment]
Здесь дёрганье сборки не подойдёт, здесь надо твои исправления дотащить до мастера.
@Sergey-Buyanov , ты когда планируешь обновлять мастер из dev'а?

**Comment by Sergey-Buyanov** [comment]
Вчера смержил в master
https://ci.appveyor.com/project/AnatolyKulakov/server/builds/19414508
Но на docker hub похоже не залилось

**Comment by kulakovt** [comment]
Да, на докер-хабе старая версия. @d2funlife , есть идеи почему образ до хаба не доехал?

**Comment by Sergey-Buyanov** [comment]
Похоже step deploy_script  нужно использовать секции deploy. Сейчас у нас там deploy: off
Link: https://www.appveyor.com/docs/appveyor-yml/

**Comment by d2funlife** [comment]
> Вчера смержил в master
> https://ci.appveyor.com/project/AnatolyKulakov/server/builds/19414508
> Но на docker hub похоже не залилось

этот билд содержит исключительно windows платформу.

**Comment by d2funlife** [comment]
Посмотрю конфигурацию appveyor. Либо взаимоисключения веток отрабатывает не верно, либо действительно проблема в секции deploy

**Comment by d2funlife** [comment]
Doocker интеграция отработала [hub](https://hub.docker.com/r/dotnetru/server/tags/) + [appveyor](https://ci.appveyor.com/project/AnatolyKulakov/server/build/job/ldvdmxru382xtc29)

**Comment by Sergey-Buyanov** [comment]
> Doocker интеграция отработала [hub](https://hub.docker.com/r/dotnetru/server/tags/) + [appveyor](https://ci.appveyor.com/project/AnatolyKulakov/server/build/job/ldvdmxru382xtc29)

Супер!

**Comment by kulakovt** [comment]
Блин, у нас в [Swagger'е](https://dotnetru.azurewebsites.net/swagger/) не видно полную версию. @Sergey-Buyanov можешь её как нибудь добавить туда, когда будет возможность?

**Comment by Sergey-Buyanov** [comment]
Да, пока у нас был добавлен только контроллер для meetup, для примера. Остальные тоже можно добавить. Хотел как раз засинхронизировать WebApi contract c domain model и сделать реализацию вызовов. Тогда в рамках той задачи сделаю

**Comment by kulakovt** [comment]
Настроил автоматический деплой в Ажур, как только появляется новый контейнер в hub'е.
Судя по логам, работает. Визуально пока без полной версии не различить :)

**Comment by Sergey-Buyanov** [comment]
@d2funlife вопрос
`WARNING! Your password will be stored unencrypted in /home/appveyor/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
Login Succeeded
Push image to docker hub`
Предупреждает, что  на build machine пароль в открытом в виде для docker hub?
Не в курсе, легко использовать потом нам какой-нибудь credential helper?

**Comment by d2funlife** [comment]
Я изучу этот вопрос, поправлю. Ранее такого предупреждения у меня не было. На той же странице с credentials store указан логин посредством stdin [документация](https://docs.docker.com/engine/reference/commandline/login/#provide-a-password-using-stdin) и отсутствуют данные о предупреждении. По факту получится, что у нас есть зашифрованный пароль, который stdin'ом попадает в логин, в изолированном, временном окружении ubuntu и credential store решит проблему сохранности в этом окружении.

**Comment by Sergey-Buyanov** [comment]
Ok.  Напиши тогда, когда прояснится, что можно сделать

**Comment by Sergey-Buyanov** [comment]
Создал issue для этого https://github.com/DotNetRu/Server/issues/45, т.к. эту закрываю
