### ISSUE TITLE
Добавить в проект CodeAnalysis

### ISSUE THREAD

**Issue by Sergey-Buyanov** [DotNetRu/Server#18]
Для автоматической проверки кода на наличие ошибок нужно настроить CodeAnalysis в проекте
[Sample](https://carlos.mendible.com/2017/08/24/net-core-code-analysis-and-stylecop/)

**Comment by Sergey-Buyanov** [comment]
Настройки правил для StyleCop и Resharper, находятся в .editorconfig, DotNetRu.Server.ruleset, DotNetRu.Server.sln.DotSettings

**Comment by kulakovt** [comment]
DotNetRu.Server.ruleset — это скорее всего FxCop.
А почему понадобился DotSettings? Разве ReSharper не полностью [перенёс свои правила в editconfig](https://blog.jetbrains.com/dotnet/2018/04/06/code-style-settings-roslyn-conventions-editorconfig/)?

**Comment by kulakovt** [comment]
@Sergey-Buyanov

**Comment by Sergey-Buyanov** [comment]
>DotNetRu.Server.ruleset — это скорее всего FxCop.
Да это ruleset для него
>А почему понадобился DotSettings?
Там находится настройка, что надо брать конфигурацию из editorconfig ) + дополнительные опции, которых нельзя сейчас указать в editorconfig (По крайне мере не нашёл способа их указать): Know words, некоторые настройки анализа для Resharper.
