### ISSUE TITLE
Изучить возможность просмотра логов Serilog в Azure

### ISSUE THREAD

**Issue by Sergey-Buyanov** [DotNetRu/Server#20]
Так как планируем запускать приложение в Azure, то хотелось бы узнать о вариантах просмотра логов приложения. В частности, сгенерированных Serilog.
[Полезная ссылка](https://blogs.msdn.microsoft.com/webdev/2017/04/26/asp-net-core-logging/)

**Comment by kulakovt** [comment]
[Log Analytics](https://azure.microsoft.com/en-us/services/log-analytics/) — Transform your log data into insights and action. Может быть интересным.

**Comment by egorikas** [comment]
В связи с тем, что произошел бескровный переворот и реализация сервера была изменена. Данная задача признается устаревшей и не соответствующей духу времени.
