### ISSUE TITLE
Настроить сборку WebApi из контракта Rest API

### ISSUE THREAD

**Issue by Sergey-Buyanov** [DotNetRu/Server#23]
Для синхронизации Rest API в swagger [MeetupManagementService.yaml](https://github.com/DotNetRu/Server/blob/features/fb-22/Contract/MeetupManagementService.yaml) c кодом нужно сделать возможность автоматическую генерацию сборки  [DotNetRu.MeetupManagement.WebApi.Contract](https://github.com/DotNetRu/Server/blob/features/fb-22/src/MeetupManagement/DotNetRu.MeetupManagement.WebApi.Contract) на appveyour 
Для генерации используется [MeetupManagementContract.bat](https://github.com/DotNetRu/Server/blob/features/fb-22/build/codegen/MeetupManagement/MeetupManagementContract.bat)
На данный момент запускается из директория, где лежит bat

Для реализации возможно несколько вариантов:
1) Настроить запуск перегенарации сборки (и её build), только при изменении [MeetupManagementService.yaml](https://github.com/DotNetRu/Server/blob/features/fb-22/Contract/MeetupManagementService.yaml) 
  Если проект DotNetRu.MeetupManagement.WebApi.Contract  собрался сделать check-in в respository
2) Оставить всё как есть, и делать check-in если DotNetRu.MeetupManagement.WebApi.Contract собрался, при этом желательно, чтобы новый build solution не запускался

3) Какой-то другой вариант

**Comment by kulakovt** [comment]
Ещё желательно не сломать сборку под Linux (`bat` файл намекает).

**Comment by Sergey-Buyanov** [comment]
Да, согласен )

**Comment by egorikas** [comment]
В связи с тем, что произошел бескровный переворот и реализация сервера была изменена. Данная задача признается устаревшей и не соответствующей духу времени.
