### ISSUE TITLE
Создать доменную модель для реализации черновиков

### ISSUE THREAD

**Issue by Sergey-Buyanov** [DotNetRu/Server#24]
Нужно создать доменную модель для реализации бизнес логики создания/редактирования/удаления черновиков (описание #13) 
Описание контракта в коде  [здесь](https://github.com/DotNetRu/Server/tree/develop/src/MeetupManagement/DotNetRu.MeetupManagement.BusinessLayer.Contract)

**Comment by a-merson** [comment]
Назначь эту таску на меня
