### ISSUE TITLE
Реализовать чтение/сохранение данных для черновиков

### ISSUE THREAD

**Issue by Sergey-Buyanov** [DotNetRu/Server#37]
Нужно спроектировать структуру БД для хранение данных для черновиков (используем EFCore CodeFirst ). А также реализовать repository на основе их контракта (PostgrateSQL, но можно для начала InMemory)
[Project](https://github.com/DotNetRu/Server/tree/develop/src/MeetupManagement/DotNetRu.MeetupManagement.Infrastructure.EFCore)

**Comment by egorikas** [comment]
В связи с тем, что произошел бескровный переворот и реализация сервера была изменена. Данная задача признается устаревшей и не соответствующей духу времени.
