### ISSUE TITLE
Изучить возможность использования credential helper при deploy на docker hub

### ISSUE THREAD

**Issue by Sergey-Buyanov** [DotNetRu/Server#45]
Сейчас при сборке в master на build машине при загрузке docker контейнер на docker hub есть warning 
`WARNING! Your password will be stored unencrypted in /home/appveyor/.docker/config.json. Configure a credential helper to remove this warning. See https://docs.docker.com/engine/reference/commandline/login/#credentials-store Login Succeeded Push image to docker hub`

Нужно понять можем ли мы использовать credentials store и если да, то использовать эту возможность

**Comment by kulakovt** [comment]
Отказались от docker'а в новой версии.
