### ISSUE TITLE
Реализовать Rest Api для черновиков

### ISSUE THREAD

**Issue by Sergey-Buyanov** [DotNetRu/Server#46]
Нужно сделать реализацию интерфейсов контроллеров [(DotNetRu.MeetupManagement.WebApi.Contract)](https://github.com/DotNetRu/Server/tree/master/src/MeetupManagement/DotNetRu.MeetupManagement.WebApi.Contract) используя [DotNetRu.MeetupManagement.Application.Contract](https://github.com/DotNetRu/Server/tree/master/src/MeetupManagement/DotNetRu.MeetupManagement.Application.Contract)

**Comment by egorikas** [comment]
В связи с тем, что произошел бескровный переворот и реализация сервера была изменена. Данная задача признается устаревшей и не соответствующей духу времени.
