### ISSUE TITLE
Работа с изображениями

### ISSUE THREAD

**Issue by egorikas** [DotNetRu/Server#54]
В данный момент, сломана загрузка изображений, со стороны клиента.
Так же, при импорте, картинки не выгружаются с гитхаба, нужно поправить эту ситуацию

**Что нужно сделать:**

1. Проанализировать [аудит](https://github.com/DotNetRu/Audit) и понять, как в нем есть изображения
2. Научиться хранить изображения в БД
3. Отредактировать импорт и импортировать изображения
4. Починить api-точки связанные с загрузкой/отдачей изображений

**Comment by MaxShoshin** [comment]
Хочу попробовать сделать.

**Comment by egorikas** [comment]
@MaxShoshin твоя
