### ISSUE TITLE
Разобраться с полем LastUpdated

### ISSUE THREAD

**Issue by egorikas** [DotNetRu/Server#56]
В некоторых моделях фронт использует LastUpdated, нужно протащить его в базу и настроить работу с ним

**Что нужно делать**

1.  Посмотреть где используется LastUpdated в моделях
2. Протащить поле в базу
3. Удалить использование git и прочего, для заполнения этого поля

**Comment by praktikon** [comment]
#71

**Comment by egorikas** [comment]
Спасибо! Реквест вмержен. Задачу можно закрывать
