### ISSUE TITLE
Написать экспортер

### ISSUE THREAD

**Issue by egorikas** [DotNetRu/Server#63]
Для окончания разработки 1 версии, необходимо разработать экспортер, который будет способен прочитать данные из базы данных, сконвертировать их в xml [(схема данных)](https://github.com/DotNetRu/Audit)

**Что нужно сделать:**

1.  Создать экспортер
2. Научить его читать данные из бд
3. Научить его сохранять данные в папке ([с сохранение структуры](https://github.com/DotNetRu/Audit))

**Comment by praktikon** [comment]
Заберу тасочку себе, если никто не против.

**Comment by egorikas** [comment]
@praktikon бери

**Comment by kulakovt** [comment]
Если будут вопросы по формату Аудита, я готов ответить

**Comment by praktikon** [comment]
По формату только один. Я уже впринцие доделал импорт в xml, и протетсил скриптом (https://github.com/DotNetRu/Audit/blob/master/test/Schema.Tests.ps1) Ошибок не выдает.
но если  тестить с помощью С#  то вот такой тест :
```
var settings = new XmlReaderSettings();
            settings.ValidationType = ValidationType.Schema;
            settings.Schemas.Add(null, @"путь к шаблону .xsd");
            XmlSchemaValidationException ex = null;
            using (XmlReader r = XmlReader.Create(@"путь в к файлу  \AlfaBank.xml", settings))
                try
                {
                    while (r.Read()) ;
                }
                catch (XmlSchemaValidationException e)
                {
                    ex = e;
                }
```
выдаст ошибку "Message: System.Xml.Schema.XmlSchemaValidationException : Type 'identity' is not declared." 
не совсем понятно что за тип и откуда берется)


UPD я уже нашел что за тип Identity. ссори за беспокойство.

**Comment by egorikas** [comment]
Спасибо @praktikon . Закрываю задачу
