### ISSUE TITLE
Написать интеграционные тесты на контроллеры

### ISSUE THREAD

**Issue by egorikas** [DotNetRu/Server#87]
В данный момент, существует поддерживать совместимость с [UI-версией проекта ](https://github.com/DotNetRu/Server/issues/83). Из-за рефакторингов и переезда с XML-хранилища на базу данных возникают баги связанные с расхождениями API.

**Что нужно**
Написать интеграционные тесты на контроллеры

**Как делать**
Предлагаю:

1. Использовать прекрасные[ возможности ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2)
2. Использовать [TestHost](https://www.infoq.com/articles/testing-aspnet-core-web-api/) 
3. Использовать InMemoryDB (уже используется в проекте)

**Результат**
Контроллеры покрыты тестами

**Comment by kulakovt** [comment]
Отказались от контроллеров в новой версии.
