### ISSUE TITLE
Добавление доменных моделей

### ISSUE THREAD

**Issue by rafaelldi** [DotNetRu/Server#98]
Вообще, могу попробовать этим заняться. Не то, что бы у меня много скилов в DDD, но курс на plurasight смотрел)
Опишите каких-нибудь подробностей и в какую часть солюшена добавлять (новый проект `.Domain`?).

**Comment by egorikas** [comment]
Да. Хорошая идея. Надо бы начать избавляться от количества проектов, которые есть)

**Comment by Sergey-Buyanov** [comment]
@rafaelldi некоторые модели уже писали (анемичные) для проекта
https://github.com/DotNetRu/Server/tree/legacy/src/MeetupManagement/DotNetRu.MeetupManagement.Domain
Можно посмотреть там.

**Comment by rafaelldi** [comment]
Видмо, модельки надо делать в соответствии с моделями в аудите?

**Comment by egorikas** [comment]
Да, скорее всего. Я пытался их сохранить похожими на аудит, но там есть расхождения

https://github.com/DotNetRu/Server/blob/903cff6884375485f02f9ba444abf15d8c3bcdcd/DotNetRuServer.Meetups.BL/Entities/Meetup.cs

**Comment by kulakovt** [comment]
@egorikas Да, модели должны точно отражать аудит. Чтобы небыло разночтений в терминологии. А в чём сейчас расхождения?

Это сейчас (как я понял) всё модели для UI. Их нужно перенести к контроллерам и оставить внешний контракт неизменным. Бизнес модели должны уметь мапиться в UI модели и обратно без всяких проблем. Во всём остальном приложении должны будут использоваться только новые бизнес модели. Важно для UI полностью оставить модели и контракт в их текущем виде.

**Comment by egorikas** [comment]
@AnatolyKulakov там есть доменная моделька, которую я делал с оглядкой на аудит и есть сущности для UI, например MeetupVM и вот *VM модель уже сделана полностью для UI (со всеми костылями), а импортируется в базу складывается через доменные модели. В чем конкретно расхождения я уже не помню, надо сравнивать, возможно я ошибаюсь

**Comment by kulakovt** [comment]
@egorikas Тогда сформулируй что нужно сделать чтобы во всех интеграциях (например) работать с моделями похожими на аудит? А UI модели желательно вынести так чтобы о них кроме контроллеров никто не знал и не мог по ошибке заиспользовать.

**Comment by egorikas** [comment]
@AnatolyKulakov @rafaelldi 
![image](https://user-images.githubusercontent.com/6932844/68542976-a8473880-03c2-11ea-9495-635c046f189d.png)
У нас есть такой проект и там лежат все модели проекта. Они как POCO сделаны, через них импортируется в базу. Если что-то накручивать, накручивать с этой стороны нужно. Все что *VM.cs это по-сути для фронта

**Comment by kulakovt** [comment]
Это конечно лучше чем *VM*, но как-то не очень на Аудит похоже.

```cs
public class Speaker
{
        // Не бывает никакого int Id
        public int Id { get; set; }
        // Это должно называться "Id"
        public string ExportId { get; set; }

        // Это должно быть типа System.Uri
        public string CompanyUrl { get; set; }

        // Как получить из этого Картинку для интеграции?
        public int AvatarId { get; set; }
        // Этого нет в Аудите
        public DateTime LastUpdateDate { get; set; }
    }
```

**Comment by egorikas** [comment]
Мы же с тобой обсуждали, что из-за того, что базу используем, сделали так

Можно дропнуть int id и переключиться на стринги

Это моделька по которой раскладывается в базе, но я тебя понял, чего ты хочешь

**Comment by kulakovt** [comment]
То, что это нужно для хранения я понимаю. Но мне кажется странным что хранилище диктует то, как должны выглядеть наши бизнес-объекты. Это ничем не лучше того, что UI нам будет сообщать требования к бизнес-модели. С таким же точно успехом можно и _VM_ модели использовать везде, хранить в базе, делать логику.

Может быть имеет смысл выделить нормальный бизнес-домен, который не будет зависеть ни от Ханилища, ни от UI'я? И тогда мы сможешь безболезненно их менять. Иначе мы не сможем ни отказаться от MSSQL, ни от Angular UI без переделывания всей логики и всех интеграций. А так как тестов у нас нет, это просто убьёт всю функциональность.

**Comment by ilabutin** [comment]
Мне такая модель (которую @AnatolyKulakov хочет) потребуется для экспорта - там как раз 1-в-1 из Аудита брать. Я на следующей неделе планировал экспортом заняться - заодно могу и модель написать нормальную.

**Comment by kulakovt** [comment]
Изначально мы планировали делать 2 домена: Черновики (#13) и Чистовики (#29).

> **TODO:** Надо подумать на названиями, чтобы они правильно отразились в коде. "Чистовики" надо точно изменить перед реализацией.

Перед созданием модели нужно обсудить дальнейшее соответствие этим планам и актуализировать epics.

**Comment by rafaelldi** [comment]
Я, кстати, сравнивал те модели, которые есть `Entities` и в аудите.
В `Community` нет полей с ссылками на соц сети: `VkUrl`, `TwitterUrl`, `TelegramChannelUrl`, `TelegramChatUrl`, `MeetupComUrl`, `TimePadUrl`, а в `Venue` есть поле `City`, которого нет [тут](https://github.com/DotNetRu/Audit/blob/master/schemas/Venue.xsd).

**Comment by ilabutin** [comment]
Посмотрел внимательно на наши модели. Кажется что нужно делать следующее:
1. Создать доменные модели в проекте `DotNetRuServer.Meetups.BL`. Назвать папку, скажем, `DomainModel`. Тут будет чисто модель типа такой:
```
    public class Meetup
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string CommunityId { get; set; }
        public List<Friend> Friends { get; set; }

        public Venue Venue { get; set; }

        public List<Session> Sessions { get; set; }
    }

    public class Session
    {
        public Talk Talk { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
    }
```

2. В терминах этой модели выразить все `IBlaBlaRepository` и `IBlaBlaService` в том же проекте.

3. То что было `Entities` на скриншоте выше в обсуждении - перенести в проект `DotNetRuServer.Meetups.DAL`. Это деталь реализации хранения именно в БД.

4. То что живет в `Models` в проекте `DotNetRuServer.Meetups.BL` перенести в проект где контроллеры `DotNetRuServer`, т.к. это модели для них.

В результате получится что контроллеры будут общаться со слоем сервисов в терминах DomainModel, и слой сервисов будет общаться со слоем хранения в терминах той же DomainModel. Контроллеры будут конвертить в свои `BlaBlaVm` модели, а слой хранения в свои `Entities`.

Все интеграции и экспорты/импорты должны зависеть только от DomainModel.

Выглядит ли это разумным?
@AnatolyKulakov @egorikas

**Comment by kulakovt** [comment]
Да, очень похоже на правду.

Желательно спрятать (уровнем доступа или отсутствием ссылки на сборку) DAL и UI модели так чтобы их физически нельзя было заиспользовать в BL (т.е. ошибиться в выборе модели для интеграции).

Это довольно большая и травмоопасная переделка. Может пора задуматься о тестах? Хотя бы гарантирующих контракт для UI. Чтобы соседняя команда не осталась со сломанным Сервером.

**Comment by ilabutin** [comment]
Тесты дело хорошее. Модели-то мы сохраним без изменений им. А что мы хотим тестировать? Что контроллеры всё еще возвращают нужные данные если сервисы вернули правильные данные?
Так мы будем переделывать интерфейс сервисов (на BL модели) и тесты тоже переписывать в итоге.

**Comment by kulakovt** [comment]
Хочется хотя бы тест на то, что из контроллера со списком всех Сообществ возвращатся больше нуля сообществ. Этот тест закрыл бы большинство проблем, которые у нас были за последнее время:

- поменяли контракт на сервере;
- не зарегистрировались API контроллеры;
- неправильно регистрировались классы поэтому Dependency Container падал;
- не отрабатывал автоматический импорт из GitHub, потому что добавилось новое сообщество;
- и т.д.

В идеале бы хотелось иметь гарантии что контракт с точки зрения UI останется неизменным. Есть большой шанс забыть перемапить поля, потерять `int ID` и прочее.

**Comment by kulakovt** [comment]
В новой версии приложения доменные модели будут другие
